apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-azure-app-config
  namespace: default
  labels:
    app: k8s-azure-app
data:
  app.properties: |
    environment=production
    log.level=info
    app.version=1.0.0
  nginx.conf: |
    upstream backend {
        server k8s-azure-app-service:80;
    }
    
    server {
        listen 80;
        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
